"""initial tables

Revision ID: 001
Revises:
Create Date: 2026-06-04 13:57:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('parent_name', sa.String(length=50), nullable=True, comment='家长姓名'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码（bcrypt加密）'),
    sa.Column('openid', sa.String(length=100), nullable=False, comment='微信openid'),
    sa.Column('unionid', sa.String(length=100), nullable=True, comment='微信unionid'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='家长头像URL'),
    sa.Column('current_child_id', sa.BigInteger(), nullable=True, comment='当前选中的孩子ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_current_child_id'), 'user', ['current_child_id'], unique=False)
    op.create_index(op.f('ix_user_openid'), 'user', ['openid'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)

    op.create_table('child',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户表ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='孩子姓名'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='孩子年龄'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='孩子年级'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='会员状态'),
    sa.Column('member_start_time', sa.DateTime(), nullable=True, comment='会员开始时间'),
    sa.Column('member_expire_time', sa.DateTime(), nullable=True, comment='会员到期时间'),
    sa.Column('ar_level', sa.Numeric(precision=3, scale=1), nullable=True, comment='AR阅读等级'),
    sa.Column('deposit_status', sa.SmallInteger(), nullable=True, comment='押金状态'),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='押金金额'),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True, comment='分配的老师ID'),
    sa.Column('venue_id', sa.BigInteger(), nullable=True, comment='所属场馆ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_status'), 'child', ['status'], unique=False)
    op.create_index(op.f('ix_child_teacher_id'), 'child', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_child_user_id'), 'child', ['user_id'], unique=False)
    op.create_index(op.f('ix_child_venue_id'), 'child', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_venue_id'), table_name='child')
    op.drop_index(op.f('ix_child_user_id'), table_name='child')
    op.drop_index(op.f('ix_child_teacher_id'), table_name='child')
    op.drop_index(op.f('ix_child_status'), table_name='child')
    op.drop_table('child')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_openid'), table_name='user')
    op.drop_index(op.f('ix_user_current_child_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
