"""005_system_config_book_format

Revision ID: 027c51baf3f8
Revises: 13e6c307ca84
Create Date: 2026-06-04 22:57:47.012589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "027c51baf3f8"
down_revision: Union[str, Sequence[str], None] = "13e6c307ca84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_config",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_key", sa.String(length=50), nullable=False, comment="配置键"),
        sa.Column(
            "config_value", sa.String(length=255), nullable=False, comment="配置值"
        ),
        sa.Column(
            "config_type",
            sa.String(length=20),
            nullable=True,
            comment="值类型: int/string/bool/json",
        ),
        sa.Column(
            "description", sa.String(length=255), nullable=True, comment="配置说明"
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_config_config_key"),
        "system_config",
        ["config_key"],
        unique=True,
    )
    op.add_column(
        "book",
        sa.Column(
            "format",
            sa.SmallInteger(),
            nullable=True,
            comment="图书格式: 0=电子+纸质 1=仅电子 2=仅纸质",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "format")
    op.drop_index(op.f("ix_system_config_config_key"), table_name="system_config")
    op.drop_table("system_config")
    # ### end Alembic commands ###
