"""010_quiz_question

Revision ID: 0c384573bb3d
Revises: bc124288ce19
Create Date: 2026-06-05 17:58:52.765004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c384573bb3d"
down_revision: Union[str, Sequence[str], None] = "bc124288ce19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_question",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("quiz_id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("question_order", sa.Integer(), nullable=True, comment="题目顺序"),
        sa.Column(
            "child_answer",
            sa.String(length=1),
            nullable=True,
            comment="孩子作答 A/B/C/D",
        ),
        sa.Column(
            "is_correct", sa.SmallInteger(), nullable=True, comment="是否正确 1=对 0=错"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quiz.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_question_quiz_id"), "quiz_question", ["quiz_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_question_quiz_id"), table_name="quiz_question")
    op.drop_table("quiz_question")
    # ### end Alembic commands ###
