"""004_v2_vocabulary_voice_relations

Revision ID: 13e6c307ca84
Revises: 746bf6b04db7
Create Date: 2026-06-04 22:15:13.493555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13e6c307ca84"
down_revision: Union[str, Sequence[str], None] = "746bf6b04db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
