"""order add parent_course_time_id (B3 slot link)

Revision ID: 18d299533269
Revises: 53490c8cb715
Create Date: 2026-07-26 11:21:53.408313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18d299533269"
down_revision: Union[str, Sequence[str], None] = "53490c8cb715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "parent_course_time_id",
            sa.BigInteger(),
            nullable=True,
            comment="亲子课时段ID（B3 关联，名额/退款校验用）",
        ),
    )
    op.create_foreign_key(
        None, "order", "parent_course_time", ["parent_course_time_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "parent_course_time_id")
    # ### end Alembic commands ###
