"""001_initial_all_tables

Revision ID: 4b61143c9ad0
Revises: 
Create Date: 2026-06-04 17:08:37.387291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b61143c9ad0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='活动名称'),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='类型: 0=免费 1=收费'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面图URL'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('venue_id', sa.BigInteger(), nullable=True, comment='场馆ID'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='最大参与人数'),
    sa.Column('current_participants', sa.Integer(), nullable=True, comment='当前报名人数'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格(收费活动)'),
    sa.Column('description', sa.Text(), nullable=True, comment='活动详情'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='活动地点'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('isbn', sa.String(length=20), nullable=False, comment='ISBN号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='书名'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='作者'),
    sa.Column('publisher', sa.String(length=100), nullable=True, comment='出版社'),
    sa.Column('ar_value', sa.Numeric(precision=3, scale=1), nullable=False, comment='AR阅读等级'),
    sa.Column('lexile_value', sa.Integer(), nullable=True, comment='蓝思值'),
    sa.Column('age_min', sa.SmallInteger(), nullable=False, comment='适合最小年龄'),
    sa.Column('age_max', sa.SmallInteger(), nullable=False, comment='适合最大年龄'),
    sa.Column('theme', sa.String(length=50), nullable=True, comment='主题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='内容简介'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面URL'),
    sa.Column('total_pages', sa.Integer(), nullable=True, comment='总页数'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_ar_value'), 'book', ['ar_value'], unique=False)
    op.create_index(op.f('ix_book_isbn'), 'book', ['isbn'], unique=True)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('parent_name', sa.String(length=50), nullable=True, comment='家长姓名'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号（微信登录用户可后续补充）'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码（bcrypt加密）'),
    sa.Column('openid', sa.String(length=100), nullable=False, comment='微信openid'),
    sa.Column('unionid', sa.String(length=100), nullable=True, comment='微信unionid'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='家长头像URL'),
    sa.Column('current_child_id', sa.BigInteger(), nullable=True, comment='当前选中的孩子ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_current_child_id'), 'user', ['current_child_id'], unique=False)
    op.create_index(op.f('ix_user_openid'), 'user', ['openid'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('child',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='孩子姓名'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='孩子年龄(3-15)'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='年级'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='会员状态'),
    sa.Column('member_start_time', sa.DateTime(), nullable=True, comment='会员开始时间'),
    sa.Column('member_expire_time', sa.DateTime(), nullable=True, comment='会员到期时间'),
    sa.Column('ar_level', sa.Numeric(precision=3, scale=1), nullable=True, comment='AR阅读等级'),
    sa.Column('deposit_status', sa.SmallInteger(), nullable=True, comment='押金状态'),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='押金金额'),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True, comment='指导老师ID'),
    sa.Column('venue_id', sa.BigInteger(), nullable=True, comment='所属场馆ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_user_id'), 'child', ['user_id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('book_id', sa.BigInteger(), nullable=False, comment='图书ID'),
    sa.Column('venue_id', sa.BigInteger(), nullable=True, comment='所属场馆ID'),
    sa.Column('barcode', sa.String(length=32), nullable=False, comment='图书条形码'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='馆藏状态'),
    sa.Column('location', sa.String(length=50), nullable=True, comment='馆内位置(如A区3层)'),
    sa.Column('purchase_time', sa.DateTime(), nullable=True, comment='采购时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_barcode'), 'collection', ['barcode'], unique=True)
    op.create_index(op.f('ix_collection_book_id'), 'collection', ['book_id'], unique=False)
    op.create_index(op.f('ix_collection_venue_id'), 'collection', ['venue_id'], unique=False)
    op.create_table('activity_enrollment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('activity_id', sa.BigInteger(), nullable=False, comment='活动ID'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='孩子ID'),
    sa.Column('ticket_code', sa.String(length=32), nullable=False, comment='电子门票码'),
    sa.Column('sign_in_time', sa.DateTime(), nullable=True, comment='签到时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态: 0=已报名 1=已签到 2=已取消'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_index(op.f('ix_activity_enrollment_activity_id'), 'activity_enrollment', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_enrollment_child_id'), 'activity_enrollment', ['child_id'], unique=False)
    op.create_table('borrow',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='孩子ID'),
    sa.Column('collection_id', sa.BigInteger(), nullable=False, comment='馆藏ID'),
    sa.Column('borrow_time', sa.DateTime(), nullable=True, comment='借阅时间'),
    sa.Column('due_time', sa.DateTime(), nullable=False, comment='应还日期'),
    sa.Column('return_time', sa.DateTime(), nullable=True, comment='实际归还时间'),
    sa.Column('renew_count', sa.SmallInteger(), nullable=True, comment='续借次数(最多1次)'),
    sa.Column('last_renew_time', sa.DateTime(), nullable=True, comment='最近续借时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='借阅状态'),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='罚款金额'),
    sa.Column('fine_paid', sa.SmallInteger(), nullable=True, comment='罚款是否已支付'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作老师ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_child_id'), 'borrow', ['child_id'], unique=False)
    op.create_index(op.f('ix_borrow_collection_id'), 'borrow', ['collection_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='孩子ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='订单类型'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='订单金额(元)'),
    sa.Column('pay_status', sa.SmallInteger(), nullable=True, comment='支付状态'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('pay_type', sa.SmallInteger(), nullable=True, comment='支付方式: 1=微信支付 2=对公转账'),
    sa.Column('trade_no', sa.String(length=64), nullable=True, comment='第三方交易流水号'),
    sa.Column('refund_status', sa.SmallInteger(), nullable=True, comment='退款状态'),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='已退款金额'),
    sa.Column('refund_time', sa.DateTime(), nullable=True, comment='退款完成时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='订单备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_child_id'), 'order', ['child_id'], unique=False)
    op.create_index(op.f('ix_order_order_no'), 'order', ['order_no'], unique=True)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='孩子ID'),
    sa.Column('book_id', sa.BigInteger(), nullable=False, comment='图书ID'),
    sa.Column('collection_id', sa.BigInteger(), nullable=True, comment='分配的馆藏ID'),
    sa.Column('reserve_time', sa.DateTime(), nullable=True, comment='预约时间'),
    sa.Column('expire_time', sa.DateTime(), nullable=False, comment='预约到期时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='预约状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_book_id'), 'reservation', ['book_id'], unique=False)
    op.create_index(op.f('ix_reservation_child_id'), 'reservation', ['child_id'], unique=False)
    op.create_table('refund_application',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='订单ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='孩子ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='原订单金额'),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='应退金额'),
    sa.Column('used_days', sa.Integer(), nullable=True, comment='已使用天数'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='退款原因'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='管理员备注'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='审核状态'),
    sa.Column('admin_id', sa.BigInteger(), nullable=True, comment='审核管理员ID'),
    sa.Column('audit_time', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_application_order_id'), 'refund_application', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_application_user_id'), 'refund_application', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_application_user_id'), table_name='refund_application')
    op.drop_index(op.f('ix_refund_application_order_id'), table_name='refund_application')
    op.drop_table('refund_application')
    op.drop_index(op.f('ix_reservation_child_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_book_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_order_no'), table_name='order')
    op.drop_index(op.f('ix_order_child_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_borrow_collection_id'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_child_id'), table_name='borrow')
    op.drop_table('borrow')
    op.drop_index(op.f('ix_activity_enrollment_child_id'), table_name='activity_enrollment')
    op.drop_index(op.f('ix_activity_enrollment_activity_id'), table_name='activity_enrollment')
    op.drop_table('activity_enrollment')
    op.drop_index(op.f('ix_collection_venue_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_book_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_barcode'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_child_user_id'), table_name='child')
    op.drop_table('child')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_openid'), table_name='user')
    op.drop_index(op.f('ix_user_current_child_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_isbn'), table_name='book')
    op.drop_index(op.f('ix_book_ar_value'), table_name='book')
    op.drop_table('book')
    op.drop_table('activity')
    # ### end Alembic commands ###
