"""fix damage reviewed_at to datetime

Revision ID: 53490c8cb715
Revises: b9f196875c6a
Create Date: 2026-07-26 10:35:10.406039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "53490c8cb715"
down_revision: Union[str, Sequence[str], None] = "b9f196875c6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book_damage_report",
        "reviewed_at",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=30),
        type_=sa.DateTime(),
        existing_comment="审核时间",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book_damage_report",
        "reviewed_at",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=30),
        existing_comment="审核时间",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
