"""028_add_token_generation_and_user_status

Revision ID: 5a5e91684fe9
Revises: 027_base_col_comments
Create Date: 2026-07-22 23:32:04.532566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a5e91684fe9"
down_revision: Union[str, Sequence[str], None] = "027_base_col_comments"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin",
        sa.Column(
            "token_generation",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Token版本号，改密码/禁用时+1使旧Token失效",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "status",
            sa.SmallInteger(),
            server_default="1",
            nullable=False,
            comment="1=启用 0=禁用",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "token_generation",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Token版本号，改密码/禁用时+1使旧Token失效",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "token_generation")
    op.drop_column("user", "status")
    op.drop_column("admin", "token_generation")
    # ### end Alembic commands ###
