"""007_teacher_model

Revision ID: 6822d63b6499
Revises: 850a4d67b4cf
Create Date: 2026-06-05 13:51:47.186956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6822d63b6499"
down_revision: Union[str, Sequence[str], None] = "850a4d67b4cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=50), nullable=False, comment="老师姓名"),
        sa.Column("phone", sa.String(length=11), nullable=False, comment="手机号"),
        sa.Column("venue_id", sa.BigInteger(), nullable=False, comment="所属场馆ID"),
        sa.Column("avatar", sa.String(length=255), nullable=True, comment="头像URL"),
        sa.Column("introduction", sa.Text(), nullable=True, comment="老师简介"),
        sa.Column(
            "expertise", sa.String(length=255), nullable=True, comment="擅长领域"
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teacher_schedule",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("teacher_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "weekday",
            sa.SmallInteger(),
            nullable=False,
            comment="星期几: 1=周一 ... 7=周日",
        ),
        sa.Column(
            "start_time", sa.String(length=10), nullable=False, comment="开始时间 HH:MM"
        ),
        sa.Column(
            "end_time", sa.String(length=10), nullable=False, comment="结束时间 HH:MM"
        ),
        sa.Column(
            "is_available", sa.SmallInteger(), nullable=True, comment="0=不可用 1=可用"
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_schedule_teacher_id"),
        "teacher_schedule",
        ["teacher_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teacher_schedule_teacher_id"), table_name="teacher_schedule")
    op.drop_table("teacher_schedule")
    op.drop_table("teacher")
    # ### end Alembic commands ###
