"""003_v2_vocabulary_voice

Revision ID: 746bf6b04db7
Revises: a28020b0f4b7
Create Date: 2026-06-04 21:25:31.636177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "746bf6b04db7"
down_revision: Union[str, Sequence[str], None] = "a28020b0f4b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionary_word",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("phonetic", sa.String(length=100), nullable=True, comment="音标"),
        sa.Column("audio_url", sa.String(length=255), nullable=True, comment="发音URL"),
        sa.Column(
            "part_of_speech", sa.String(length=20), nullable=True, comment="词性"
        ),
        sa.Column(
            "chinese_meaning", sa.String(length=255), nullable=False, comment="中文释义"
        ),
        sa.Column("example_sentence", sa.Text(), nullable=True, comment="例句"),
        sa.Column("level", sa.String(length=10), nullable=True, comment="难度(A1-C2)"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dictionary_word_word"), "dictionary_word", ["word"], unique=True
    )
    op.create_table(
        "user_vocabulary",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("word_id", sa.BigInteger(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=True, comment="来源图书"),
        sa.Column(
            "status", sa.SmallInteger(), nullable=True, comment="0=学习中 1=已掌握"
        ),
        sa.Column("lookup_count", sa.Integer(), nullable=True, comment="查询次数"),
        sa.Column("last_review_time", sa.DateTime(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["dictionary_word.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_vocabulary_child_id"),
        "user_vocabulary",
        ["child_id"],
        unique=False,
    )
    op.create_table(
        "voice_recording",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=True, comment="关联页面"),
        sa.Column("text_content", sa.Text(), nullable=False, comment="朗读文本"),
        sa.Column(
            "audio_url", sa.String(length=255), nullable=False, comment="录音URL"
        ),
        sa.Column(
            "duration_seconds", sa.Integer(), nullable=False, comment="录音时长(秒)"
        ),
        sa.Column(
            "pronunciation_score",
            sa.Numeric(precision=3, scale=1),
            nullable=True,
            comment="发音评分",
        ),
        sa.Column(
            "fluency_score",
            sa.Numeric(precision=3, scale=1),
            nullable=True,
            comment="流利度评分",
        ),
        sa.Column(
            "completeness_score",
            sa.Numeric(precision=3, scale=1),
            nullable=True,
            comment="完整度评分",
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_recording_child_id"),
        "voice_recording",
        ["child_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_recording_child_id"), table_name="voice_recording")
    op.drop_table("voice_recording")
    op.drop_index(op.f("ix_user_vocabulary_child_id"), table_name="user_vocabulary")
    op.drop_table("user_vocabulary")
    op.drop_index(op.f("ix_dictionary_word_word"), table_name="dictionary_word")
    op.drop_table("dictionary_word")
    # ### end Alembic commands ###
