"""008_reading_submission_wordcount

Revision ID: 7641c1e2bb62
Revises: 920c298fd68f
Create Date: 2026-06-09 18:21:39.538374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7641c1e2bb62'
down_revision: Union[str, Sequence[str], None] = '920c298fd68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_submission', sa.Column('word_count', sa.Integer(), nullable=True, comment='该本书的单词数（积分用）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_submission', 'word_count')
    # ### end Alembic commands ###
