"""008_bugfixes_reservation_expire_at

Revision ID: 7f633945e2ee
Revises: 6822d63b6499
Create Date: 2026-06-05 17:07:30.089713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f633945e2ee'
down_revision: Union[str, Sequence[str], None] = '6822d63b6499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('expire_at', sa.DateTime(), nullable=True, comment='精确过期时间点（用于定时清理）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'expire_at')
    # ### end Alembic commands ###
