"""006_v3_advancement_system

Revision ID: 850a4d67b4cf
Revises: 027c51baf3f8
Create Date: 2026-06-05 12:31:14.449352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850a4d67b4cf'
down_revision: Union[str, Sequence[str], None] = '027c51baf3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='成就名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='成就描述'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='成就类型'),
    sa.Column('badge_icon', sa.String(length=255), nullable=True, comment='徽章图标URL'),
    sa.Column('badge_emoji', sa.String(length=10), nullable=True, comment='徽章Emoji'),
    sa.Column('trigger_condition', sa.String(length=255), nullable=True, comment='触发条件JSON'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='级别名称'),
    sa.Column('badge_icon', sa.String(length=255), nullable=True, comment='徽章图标URL'),
    sa.Column('badge_emoji', sa.String(length=10), nullable=True, comment='徽章Emoji'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号（越小越初级）'),
    sa.Column('required_books', sa.Integer(), nullable=True, comment='需要读完几本书才能晋级'),
    sa.Column('required_quiz_pass_rate', sa.Numeric(precision=3, scale=2), nullable=True, comment='测验最低通过率'),
    sa.Column('require_teacher_review', sa.Boolean(), nullable=True, comment='是否需要老师审核'),
    sa.Column('max_borrow_count', sa.Integer(), nullable=True, comment='最大同时借阅数'),
    sa.Column('max_ar_level', sa.Numeric(precision=3, scale=1), nullable=True, comment='最大可读AR等级'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False, comment='题目文本'),
    sa.Column('option_a', sa.String(length=255), nullable=False, comment='选项A'),
    sa.Column('option_b', sa.String(length=255), nullable=False, comment='选项B'),
    sa.Column('option_c', sa.String(length=255), nullable=True, comment='选项C'),
    sa.Column('option_d', sa.String(length=255), nullable=True, comment='选项D'),
    sa.Column('correct_answer', sa.String(length=1), nullable=False, comment='正确答案(A/B/C/D)'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='答案解析'),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True, comment='难度1-5'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者ID（老师）'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_book_id'), 'question_bank', ['book_id'], unique=False)
    op.create_table('child_achievement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True, comment='获得时间'),
    sa.Column('context_data', sa.String(length=255), nullable=True, comment='上下文JSON（如读完第几本书）'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_achievement_child_id'), 'child_achievement', ['child_id'], unique=False)
    op.create_table('child_level',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True, comment='达到该级别的时间'),
    sa.Column('books_read_at_level', sa.Integer(), nullable=True, comment='在该级别已读完的书数'),
    sa.Column('quizzes_passed_at_level', sa.Integer(), nullable=True, comment='在该级别通过的测验数'),
    sa.Column('is_current', sa.Boolean(), nullable=True, comment='是否当前级别'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_level_child_id'), 'child_level', ['child_id'], unique=False)
    op.create_table('reading_submission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True, comment='负责审核的老师ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='审核状态'),
    sa.Column('teacher_comment', sa.Text(), nullable=True, comment='老师评语'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_submission_child_id'), 'reading_submission', ['child_id'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True, comment='出卷老师ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True, comment='题目总数'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确数'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='正确率'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['reading_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_child_id'), 'quiz', ['child_id'], unique=False)
    op.create_table('quiz_answer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False, comment='孩子选择的答案(A/B/C/D)'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否正确'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answer_quiz_id'), 'quiz_answer', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answer_quiz_id'), table_name='quiz_answer')
    op.drop_table('quiz_answer')
    op.drop_index(op.f('ix_quiz_child_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_reading_submission_child_id'), table_name='reading_submission')
    op.drop_table('reading_submission')
    op.drop_index(op.f('ix_child_level_child_id'), table_name='child_level')
    op.drop_table('child_level')
    op.drop_index(op.f('ix_child_achievement_child_id'), table_name='child_achievement')
    op.drop_table('child_achievement')
    op.drop_index(op.f('ix_question_bank_book_id'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_table('level')
    op.drop_table('achievement')
    # ### end Alembic commands ###
