"""007_child_english_name

Revision ID: 920c298fd68f
Revises: 8aefda1affd5
Create Date: 2026-06-09 18:17:26.384535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '920c298fd68f'
down_revision: Union[str, Sequence[str], None] = '8aefda1affd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('english_name', sa.String(length=50), nullable=True, comment='孩子英文姓名'))
    op.alter_column('child', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='孩子中文姓名',
               existing_comment='孩子姓名',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('child', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='孩子姓名',
               existing_comment='孩子中文姓名',
               existing_nullable=False)
    op.drop_column('child', 'english_name')
    # ### end Alembic commands ###
