"""024_add_order_refund_remark

Revision ID: 96f200b6ed5a
Revises: d9d508402c87
Create Date: 2026-07-15 00:47:57.993218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f200b6ed5a'
down_revision: Union[str, Sequence[str], None] = 'd9d508402c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('refund_remark', sa.String(length=255), nullable=True, comment='退款备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'refund_remark')
    # ### end Alembic commands ###
