"""002_v2_reading_platform

Revision ID: a28020b0f4b7
Revises: 4b61143c9ad0
Create Date: 2026-06-04 21:19:35.044909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a28020b0f4b7"
down_revision: Union[str, Sequence[str], None] = "4b61143c9ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_page",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column(
            "content_type",
            sa.SmallInteger(),
            nullable=True,
            comment="0=文本 1=图片 2=图文混合",
        ),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column(
            "audio_url", sa.String(length=255), nullable=True, comment="该页音频URL"
        ),
        sa.Column(
            "audio_duration", sa.Integer(), nullable=True, comment="音频时长(秒)"
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_page_book_id"), "book_page", ["book_id"], unique=False
    )
    op.create_table(
        "check_in",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("check_date", sa.Date(), nullable=False),
        sa.Column(
            "check_type",
            sa.SmallInteger(),
            nullable=False,
            comment="1=阅读 2=读完 3=朗读 4=生词",
        ),
        sa.Column("reading_minutes", sa.Integer(), nullable=True),
        sa.Column("words_read", sa.Integer(), nullable=True),
        sa.Column("books_finished", sa.Integer(), nullable=True),
        sa.Column("new_words", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reading_progress",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("current_page", sa.Integer(), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("last_read_time", sa.DateTime(), nullable=True),
        sa.Column("is_finished", sa.SmallInteger(), nullable=True),
        sa.Column("finish_time", sa.DateTime(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reading_session",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column(
            "duration_seconds", sa.Integer(), nullable=True, comment="阅读时长(秒)"
        ),
        sa.Column("pages_read", sa.Integer(), nullable=True),
        sa.Column("words_read", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_session_child_id"),
        "reading_session",
        ["child_id"],
        unique=False,
    )
    op.add_column(
        "book", sa.Column("word_count", sa.Integer(), nullable=True, comment="总词数")
    )
    op.add_column(
        "book",
        sa.Column(
            "estimated_reading_minutes",
            sa.Integer(),
            nullable=True,
            comment="预计阅读时间(分钟)",
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "has_audio",
            sa.SmallInteger(),
            nullable=True,
            comment="是否配有音频: 0=无 1=有",
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "audio_url", sa.String(length=255), nullable=True, comment="整书音频URL"
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "series_name", sa.String(length=100), nullable=True, comment="所属系列"
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "difficulty_level",
            sa.String(length=10),
            nullable=True,
            comment="难度标签(入门/初级/中级/高级)",
        ),
    )
    op.add_column(
        "child",
        sa.Column(
            "total_reading_minutes", sa.Integer(), nullable=True, comment="累计阅读分钟"
        ),
    )
    op.add_column(
        "child",
        sa.Column(
            "total_words_read", sa.Integer(), nullable=True, comment="累计阅读词数"
        ),
    )
    op.add_column(
        "child",
        sa.Column(
            "total_books_finished", sa.Integer(), nullable=True, comment="累计读完本数"
        ),
    )
    op.add_column(
        "child",
        sa.Column(
            "current_streak_days", sa.Integer(), nullable=True, comment="连续打卡天数"
        ),
    )
    op.add_column(
        "child",
        sa.Column(
            "longest_streak_days", sa.Integer(), nullable=True, comment="最长连续打卡"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("child", "longest_streak_days")
    op.drop_column("child", "current_streak_days")
    op.drop_column("child", "total_books_finished")
    op.drop_column("child", "total_words_read")
    op.drop_column("child", "total_reading_minutes")
    op.drop_column("book", "difficulty_level")
    op.drop_column("book", "series_name")
    op.drop_column("book", "audio_url")
    op.drop_column("book", "has_audio")
    op.drop_column("book", "estimated_reading_minutes")
    op.drop_column("book", "word_count")
    op.drop_index(op.f("ix_reading_session_child_id"), table_name="reading_session")
    op.drop_table("reading_session")
    op.drop_table("reading_progress")
    op.drop_table("check_in")
    op.drop_index(op.f("ix_book_page_book_id"), table_name="book_page")
    op.drop_table("book_page")
    # ### end Alembic commands ###
