"""drop favorites table (D5 merged into bookshelf)

Revision ID: b9f196875c6a
Revises: db9ee05cf8bf
Create Date: 2026-07-26 07:53:30.617814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b9f196875c6a"
down_revision: Union[str, Sequence[str], None] = "db9ee05cf8bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # favorites 表存量 0 行（D5 决策：收藏并入 bookshelf 想读清单）
    # MySQL 中索引随表删除，无需单独 drop_index
    op.drop_table("favorites")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column(
            "child_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="孩子ID",
        ),
        sa.Column(
            "book_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="图书ID",
        ),
        sa.Column(
            "id", mysql.BIGINT(), autoincrement=True, nullable=False, comment="主键"
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="创建时间"),
        sa.Column("update_time", mysql.DATETIME(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted",
            mysql.SMALLINT(),
            autoincrement=False,
            nullable=True,
            comment="软删除标记: 0=正常 1=已删除",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("favorites_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["child.id"], name=op.f("favorites_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_favorites_child_id"), "favorites", ["child_id"], unique=False
    )
    # ### end Alembic commands ###
