"""009_missing_tables

Revision ID: bc124288ce19
Revises: 7f633945e2ee
Create Date: 2026-06-05 17:43:14.535592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "bc124288ce19"
down_revision: Union[str, Sequence[str], None] = "7f633945e2ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "role",
            sa.SmallInteger(),
            nullable=True,
            comment="1=管理员 2=场馆管理员 3=老师",
        ),
        sa.Column("venue_id", sa.BigInteger(), nullable=True),
        sa.Column("phone", sa.String(length=11), nullable=True),
        sa.Column("status", sa.SmallInteger(), nullable=True, comment="1=启用 0=禁用"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "operation_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("admin_id", sa.BigInteger(), nullable=True),
        sa.Column("module", sa.String(length=50), nullable=True, comment="操作模块"),
        sa.Column("operation", sa.String(length=50), nullable=True, comment="操作类型"),
        sa.Column("content", sa.String(length=500), nullable=True, comment="操作内容"),
        sa.Column("ip", sa.String(length=50), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parent_course_time",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "course_date",
            sa.String(length=10),
            nullable=False,
            comment="日期 YYYY-MM-DD",
        ),
        sa.Column(
            "start_time", sa.String(length=5), nullable=False, comment="开始时间 HH:MM"
        ),
        sa.Column(
            "end_time", sa.String(length=5), nullable=False, comment="结束时间 HH:MM"
        ),
        sa.Column("max_participants", sa.Integer(), nullable=True, comment="最大名额"),
        sa.Column(
            "current_participants", sa.Integer(), nullable=True, comment="已报名人数"
        ),
        sa.Column(
            "status",
            sa.SmallInteger(),
            nullable=True,
            comment="1=可预约 0=已满 -1=已关闭",
        ),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parent_course_time_venue_id"),
        "parent_course_time",
        ["venue_id"],
        unique=False,
    )
    op.create_table(
        "venue",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column(
            "business_hours", sa.String(length=100), nullable=False, comment="营业时间"
        ),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("cover", sa.String(length=255), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_message",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "msg_type",
            sa.SmallInteger(),
            nullable=True,
            comment="1=系统通知 2=活动通知 3=借阅通知 4=老师消息 5=阅读提醒",
        ),
        sa.Column(
            "priority", sa.SmallInteger(), nullable=True, comment="0=低 1=中 2=高"
        ),
        sa.Column("is_read", sa.SmallInteger(), nullable=True, comment="0=未读 1=已读"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_message_user_id"), "system_message", ["user_id"], unique=False
    )
    op.create_table(
        "ar_evaluation",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("ar_level", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("evaluation_date", sa.DateTime(), nullable=False),
        sa.Column("teacher_id", sa.BigInteger(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ar_evaluation_child_id"), "ar_evaluation", ["child_id"], unique=False
    )
    op.create_table(
        "guidance_record",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("teacher_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False, comment="指导内容"),
        sa.Column("guidance_date", sa.DateTime(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guidance_record_child_id"),
        "guidance_record",
        ["child_id"],
        unique=False,
    )
    op.create_table(
        "learning_report",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "report_type", sa.SmallInteger(), nullable=False, comment="1=周报 2=月报"
        ),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=True),
        sa.Column("total_words", sa.Integer(), nullable=True),
        sa.Column("books_finished", sa.Integer(), nullable=True),
        sa.Column("new_vocabulary", sa.Integer(), nullable=True),
        sa.Column("voice_practices", sa.Integer(), nullable=True),
        sa.Column("check_in_days", sa.Integer(), nullable=True),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_report_child_id"),
        "learning_report",
        ["child_id"],
        unique=False,
    )
    op.create_table(
        "observation_evaluation",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.Column("teacher_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "reading_interest",
            sa.SmallInteger(),
            nullable=False,
            comment="阅读兴趣 1-5",
        ),
        sa.Column(
            "reading_speed", sa.SmallInteger(), nullable=False, comment="阅读速度 1-5"
        ),
        sa.Column(
            "comprehension", sa.SmallInteger(), nullable=False, comment="理解能力 1-5"
        ),
        sa.Column(
            "independent_reading",
            sa.SmallInteger(),
            nullable=False,
            comment="自主阅读 1-5",
        ),
        sa.Column("total_score", sa.Integer(), nullable=False, comment="总分"),
        sa.Column(
            "result",
            sa.SmallInteger(),
            nullable=False,
            comment="1=通过 2=待定 3=不通过",
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("evaluation_date", sa.DateTime(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observation_evaluation_child_id"),
        "observation_evaluation",
        ["child_id"],
        unique=False,
    )
    op.add_column(
        "activity",
        sa.Column("is_free", sa.SmallInteger(), nullable=True, comment="1=免费 0=收费"),
    )
    op.add_column(
        "activity",
        sa.Column(
            "enroll_deadline", sa.DateTime(), nullable=True, comment="报名截止时间"
        ),
    )
    op.alter_column(
        "activity",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "activity",
        "title",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment=None,
        existing_comment="活动名称",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "type",
        existing_type=mysql.SMALLINT(),
        nullable=False,
        comment="1=读书交流 2=讲座 3=CityWalk 4=郊游 5=大会 6=其他",
        existing_comment="类型: 0=免费 1=收费",
    )
    op.alter_column(
        "activity",
        "cover",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        comment=None,
        existing_comment="封面图URL",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "start_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="开始时间",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "end_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="结束时间",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "venue_id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="场馆ID",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "max_participants",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="最大参与人数",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "current_participants",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="当前报名人数",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "price",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        comment=None,
        existing_comment="价格(收费活动)",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "description",
        existing_type=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        comment=None,
        existing_comment="活动详情",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "location",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment=None,
        existing_comment="活动地点",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "status",
        existing_type=mysql.SMALLINT(),
        comment=None,
        existing_comment="状态",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "create_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "update_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "is_deleted",
        existing_type=mysql.SMALLINT(),
        comment=None,
        existing_comment="软删除标记",
        existing_nullable=True,
    )
    op.add_column(
        "activity_enrollment",
        sa.Column("admin_remark", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "activity_enrollment",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "activity_enrollment",
        "activity_id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="活动ID",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "child_id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="孩子ID",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "ticket_code",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        comment=None,
        existing_comment="电子门票码",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "sign_in_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="签到时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "status",
        existing_type=mysql.SMALLINT(),
        comment=None,
        existing_comment="状态: 0=已报名 1=已签到 2=已取消",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "create_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "update_time",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "is_deleted",
        existing_type=mysql.SMALLINT(),
        comment=None,
        existing_comment="软删除标记",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity_enrollment",
        "is_deleted",
        existing_type=mysql.SMALLINT(),
        comment="软删除标记",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "update_time",
        existing_type=mysql.DATETIME(),
        comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "create_time",
        existing_type=mysql.DATETIME(),
        comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "status",
        existing_type=mysql.SMALLINT(),
        comment="状态: 0=已报名 1=已签到 2=已取消",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "sign_in_time",
        existing_type=mysql.DATETIME(),
        comment="签到时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_enrollment",
        "ticket_code",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
        comment="电子门票码",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "child_id",
        existing_type=mysql.BIGINT(),
        comment="孩子ID",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "activity_id",
        existing_type=mysql.BIGINT(),
        comment="活动ID",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_enrollment",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("activity_enrollment", "admin_remark")
    op.alter_column(
        "activity",
        "is_deleted",
        existing_type=mysql.SMALLINT(),
        comment="软删除标记",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "update_time",
        existing_type=mysql.DATETIME(),
        comment="更新时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "create_time",
        existing_type=mysql.DATETIME(),
        comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "status",
        existing_type=mysql.SMALLINT(),
        comment="状态",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "location",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment="活动地点",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "description",
        existing_type=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        comment="活动详情",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "price",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        comment="价格(收费活动)",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "current_participants",
        existing_type=mysql.INTEGER(),
        comment="当前报名人数",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "max_participants",
        existing_type=mysql.INTEGER(),
        comment="最大参与人数",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "venue_id",
        existing_type=mysql.BIGINT(),
        comment="场馆ID",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "end_time",
        existing_type=mysql.DATETIME(),
        comment="结束时间",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "start_time",
        existing_type=mysql.DATETIME(),
        comment="开始时间",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "cover",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        comment="封面图URL",
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "type",
        existing_type=mysql.SMALLINT(),
        nullable=True,
        comment="类型: 0=免费 1=收费",
        existing_comment="1=读书交流 2=讲座 3=CityWalk 4=郊游 5=大会 6=其他",
    )
    op.alter_column(
        "activity",
        "title",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment="活动名称",
        existing_nullable=False,
    )
    op.alter_column(
        "activity",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("activity", "enroll_deadline")
    op.drop_column("activity", "is_free")
    op.drop_index(
        op.f("ix_observation_evaluation_child_id"), table_name="observation_evaluation"
    )
    op.drop_table("observation_evaluation")
    op.drop_index(op.f("ix_learning_report_child_id"), table_name="learning_report")
    op.drop_table("learning_report")
    op.drop_index(op.f("ix_guidance_record_child_id"), table_name="guidance_record")
    op.drop_table("guidance_record")
    op.drop_index(op.f("ix_ar_evaluation_child_id"), table_name="ar_evaluation")
    op.drop_table("ar_evaluation")
    op.drop_index(op.f("ix_system_message_user_id"), table_name="system_message")
    op.drop_table("system_message")
    op.drop_table("venue")
    op.drop_index(
        op.f("ix_parent_course_time_venue_id"), table_name="parent_course_time"
    )
    op.drop_table("parent_course_time")
    op.drop_table("operation_log")
    op.drop_table("admin")
    # ### end Alembic commands ###
