"""023_final_drift_fix

Revision ID: d9d508402c87
Revises: b5f4e3d2c1a0
Create Date: 2026-07-14 14:01:41.899528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d9d508402c87"
down_revision: Union[str, Sequence[str], None] = "b5f4e3d2c1a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_config",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "system_message",
        "title",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=100
        ),
        nullable=False,
        existing_comment="标题",
    )
    op.alter_column(
        "system_message",
        "content",
        existing_type=mysql.TEXT(charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        nullable=False,
        existing_comment="内容",
    )
    op.alter_column(
        "system_message",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "teacher",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_table_comment(
        "teacher_message", existing_comment="老师消息通知表", schema=None
    )
    op.alter_column(
        "teacher_schedule",
        "teacher_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        existing_comment="老师ID",
    )
    op.alter_column(
        "teacher_schedule",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user_vocabulary",
        "child_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        existing_comment="孩子ID",
    )
    op.alter_column(
        "user_vocabulary",
        "word_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        existing_comment="词典词条ID",
    )
    op.alter_column(
        "user_vocabulary",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index("uq_user_vocabulary_child_word", table_name="user_vocabulary")
    op.create_unique_constraint(
        "uq_child_word", "user_vocabulary", ["child_id", "word_id"]
    )
    op.alter_column(
        "venue",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=100
        ),
        nullable=False,
        existing_comment="场馆名称",
    )
    op.alter_column(
        "venue",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "voice_recording",
        "child_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        existing_comment="孩子ID",
    )
    op.alter_column(
        "voice_recording",
        "book_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        existing_comment="图书ID",
    )
    op.alter_column(
        "voice_recording",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voice_recording",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "voice_recording",
        "book_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        existing_comment="图书ID",
    )
    op.alter_column(
        "voice_recording",
        "child_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        existing_comment="孩子ID",
    )
    op.alter_column(
        "venue",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "venue",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=100
        ),
        nullable=True,
        existing_comment="场馆名称",
    )
    op.drop_constraint("uq_child_word", "user_vocabulary", type_="unique")
    op.create_index(
        "uq_user_vocabulary_child_word",
        "user_vocabulary",
        ["child_id", "word_id"],
        unique=True,
    )
    op.alter_column(
        "user_vocabulary",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user_vocabulary",
        "word_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        existing_comment="词典词条ID",
    )
    op.alter_column(
        "user_vocabulary",
        "child_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        existing_comment="孩子ID",
    )
    op.alter_column(
        "teacher_schedule",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "teacher_schedule",
        "teacher_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        existing_comment="老师ID",
    )
    op.create_table_comment(
        "teacher_message", "老师消息通知表", existing_comment=None, schema=None
    )
    op.alter_column(
        "teacher",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "system_message",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "system_message",
        "content",
        existing_type=mysql.TEXT(charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        nullable=True,
        existing_comment="内容",
    )
    op.alter_column(
        "system_message",
        "title",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=100
        ),
        nullable=True,
        existing_comment="标题",
    )
    op.alter_column(
        "system_config",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
