"""fix dead_letter resolved_at to datetime, order.type comment add quarterly semiannual

Revision ID: db9ee05cf8bf
Revises: a1b2c3d4e5f6
Create Date: 2026-07-26 01:46:23.589367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "db9ee05cf8bf"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dead_letter_event",
        "resolved_at",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=30),
        type_=sa.DateTime(),
        existing_comment="解决时间",
        existing_nullable=True,
    )
    op.alter_column(
        "order",
        "type",
        existing_type=mysql.SMALLINT(),
        comment="订单类型: 1=亲子课 2=观察期 3=正式会员 4=季度会员 5=半年会员",
        existing_comment="订单类型: 1=亲子课 2=观察期 3=正式会员",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "type",
        existing_type=mysql.SMALLINT(),
        comment="订单类型: 1=亲子课 2=观察期 3=正式会员",
        existing_comment="订单类型: 1=亲子课 2=观察期 3=正式会员 4=季度会员 5=半年会员",
        existing_nullable=False,
    )
    op.alter_column(
        "dead_letter_event",
        "resolved_at",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=30),
        existing_comment="解决时间",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
