"""add_indexes_borrow_status_due_date_reservation_expire

Revision ID: f7ad15b0e774
Revises: 7a8b9c0d1e2f
Create Date: 2026-07-20 09:55:29.059721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7ad15b0e774"
down_revision: Union[str, Sequence[str], None] = "7a8b9c0d1e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_borrow_record_due_date"), "borrow_record", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_borrow_record_status"), "borrow_record", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reservation_expire_time"), "reservation", ["expire_time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservation_expire_time"), table_name="reservation")
    op.drop_index(op.f("ix_borrow_record_status"), table_name="borrow_record")
    op.drop_index(op.f("ix_borrow_record_due_date"), table_name="borrow_record")
    # ### end Alembic commands ###
